### ISSUE TITLE
Remove the uploading, just package

### ISSUE THREAD

**Issue by Typositoire** [adgear/helm-chart-resource#3]
I guess it makes sense to just let uploading be done by something like [Artifactory Resource](https://github.com/pivotalservices/artifactory-resource) instead of accounting for every flavor of helm repository.

**Comment by adgear-concourse-dev** [comment]
Stale issues rot after 30d of inactivity.
Mark the issue as fresh with `/remove-lifecycle rotten`.
Rotten issues close after an additional 30d of inactivity. (Deactivated)
If this issue is safe to close now please do so with `/close`.
Send feedback to SRE.
/lifecycle rotten
